-- MySQL Script generated by MySQL Workbench
-- 08/25/16 08:22:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema greenlight_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema greenlight_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greenlight_db` DEFAULT CHARACTER SET utf8 ;
USE `greenlight_db` ;

-- -----------------------------------------------------
-- Table `greenlight_db`.`association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenlight_db`.`association` (
  `idAssociation` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nomAssociation` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAssociation`),
  UNIQUE INDEX `idAssociation_UNIQUE` (`idAssociation` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenlight_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenlight_db`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `sex` ENUM('male', 'female', 'unassigned') NULL DEFAULT NULL,
  `type` ENUM('normal', 'mod', 'admin') NOT NULL DEFAULT 'normal',
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenlight_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenlight_db`.`project` (
  `idProjet` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idAssociation` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `medialink` VARCHAR(45) NULL DEFAULT NULL,
  `creation` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`idProjet`),
  UNIQUE INDEX `idProjet_UNIQUE` (`idProjet` ASC),
  INDEX `idAssociation_idx` (`idAssociation` ASC),
  CONSTRAINT `idAssociation`
    FOREIGN KEY (`idAssociation`)
    REFERENCES `greenlight_db`.`association` (`idAssociation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenlight_db`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenlight_db`.`donation` (
  `idDonation` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idProjet` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  `montant` INT NOT NULL,
  `validé` TINYINT(1) NOT NULL DEFAULT 0,
  `date` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`idDonation`),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idProjet_idx` (`idProjet` ASC),
  UNIQUE INDEX `idDonation_UNIQUE` (`idDonation` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `greenlight_db`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProjet`
    FOREIGN KEY (`idProjet`)
    REFERENCES `greenlight_db`.`project` (`idProjet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenlight_db`.`newsfeed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `greenlight_db`.`newsfeed` (
  `idNews` INT NOT NULL AUTO_INCREMENT,
  `idProjet1` INT NOT NULL,
  `text` LONGTEXT NOT NULL,
  `time` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`idNews`),
  INDEX `idProjet_idx` (`idProjet1` ASC),
  UNIQUE INDEX `idNews_UNIQUE` (`idNews` ASC),
  CONSTRAINT `idProjet`
    FOREIGN KEY (`idProjet1`)
    REFERENCES `greenlight_db`.`project` (`idProjet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
